### PR TITLE
Add documentation for stopwatch, stock stopwatch, alarm, interval faces

### PR DESCRIPTION
**Pull request by TheOnePerson**
This pr adds some documentation for these faces:
- stopwatch
- stock stopwatch
- alarm
- interval

It also adds [Back to top] links for easier navigation.

Order of the watch faces is somewhat arbitrary. I did not want to re-order the whole page so I fit the faces in where I found it suitable.

### CODE REVIEW

**Comment by joeycastillo** [comment]
Thanks for this! Merging :)

**Comment by joeycastillo** [comment]
Oh wait dang this is the legacy documentation site. I need to archive this. 

Can you resubmit these changes to https://github.com/joeycastillo/sensorwatch.net ?

**Comment by TheOnePerson** [comment]
Oh boy, I did not realize that! :-D
Sure, will make a new pr.

**Comment by joeycastillo** [comment]
Haha I didn’t realize it either, got as far as merging it in before I realized!

**Pull request merged**
